### ISSUE TITLE
Abiliity uses

### ISSUE THREAD

**Issue by QuantumBreed** [giffyglyph/foundry-5e-monster-maker#31]
When working with uncommon abilities i've been trying to track uses of a scaling action. However in the scaling actions the only thing that changes is the refresh rate. inputting any max and current does not track. However switching back to a non scaling action and entering the desired numbers in the normal spots allows the tracking and auto use of of resources.

**Comment by QuantumBreed** [comment]
![image](https://user-images.githubusercontent.com/30003932/124361716-82f1e880-dbfe-11eb-9a84-eca57244559c.png)

**Comment by QuantumBreed** [comment]
![image](https://user-images.githubusercontent.com/30003932/124361758-b765a480-dbfe-11eb-9764-3563a048d94b.png)

**Comment by giffyglyph** [comment]
Action uses are now synced correctly between RAW item and FMM scaling action.

**Comment by giffyglyph** [comment]
Fixed in v1.0.0. Uses are now correctly. synced.
