### ISSUE TITLE
Can't load math.js.map

### ISSUE THREAD

**Issue by ravingdragoon** [giffyglyph/foundry-5e-monster-maker#47]
I am not sure how important, or unimportant, it is, but I keep receiving the following error every time I launch my games. If I install manually and change the name from math_js.9.3.2.min.js to math.js the issue stops happening. I am not sure if this is affecting any functionality though.

DevTools failed to load source map: Could not load content for https://assets.forge-vtt.com/bazaar/modules/giffyglyphs-5e-monster-maker/1.0.0/scripts/vendors/math.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by giffyglyph** [comment]
This is just a developer warning (map files are useful for debugging) and doesn't affect any functionality. But it's worth adding the .map file in the next update to tidy up.
