### ISSUE TITLE
Scaling actions are not compatible with BetterRolls 5e

### ISSUE THREAD

**Issue by dccrain** [giffyglyph/foundry-5e-monster-maker#50]
![bug report image](https://user-images.githubusercontent.com/11513549/127698441-a36cb759-a7f3-4c57-bba0-c8b218653375.png)

When rolling a scaled action using BetterRolls 5e this error message displays. It seems the shortcode developed for the module is not compatible with the assumptions BetterRolls makes about the implementation of an action on an actor sheet.

It may be beyond the scope of your work to make it compatible with another module, but BetterRolls makes it very convenient for play as it creates a single chat card with to hit and damage, or prompts for player tokens making a saving throw.

It does make it prohibitive to use features of the module as intended because of this conflict - my group has come to expect the BetterRolls style of rolling and turning it off to be able to use scaling monster actions is not ideal.

Thanks - great work on this module

**Comment by TheDataReaper** [comment]
Hello this has been asked before and sadly due to a number of ways BR 5e has been coded it's currently very difficult to have MM work with it without some extreme reworking.
It does work well with MIDI though.

**Comment by dccrain** [comment]
Fair enough, I figured something like that would be the case. If it's not going to be something that will be done then I'll close the issue.

**Comment by TheDataReaper** [comment]
Sadly it would be hard for either due to do it too. I love BR5e myself.
Maybe in the future there can be an easier way to fix it
