### ISSUE TITLE
Add support for Better Rolls to modal roll dialogs

### ISSUE THREAD

**Issue by giffyglyph** [giffyglyph/foundry-5e-monster-maker#6]
Allow quick-roll prompts to support Better Rolls functionality.

**Comment by Lyra214** [comment]
Might be worth noting that support for midi-qol, a module wildly used in place of better rolls, would be a great idea as well.

**Comment by giffyglyph** [comment]
I don't think we can make this compatible with BetterRolls without a total rewrite/rethink of the Monster Maker. The problem is the automated shortcodes; BetterRolls builds its own roll formula in field.js, bypassing the necessary custom handlers in GmmItem:

`
  if (!formula && item) {
	  const itemData = item.data.data;
	  const flags = item.data.flags.betterRolls5e;
`

This can't be easily fixed, so closing for now until a better idea turns up.
